version: '3.8'

services:
  auth-api:
    build: ./auth-api
    expose:
      - "8000"
    environment:
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=PRFT
    networks:
      - msa-network

  users-api:
    build: ./users-api
    expose:
      - "8083"
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
    networks:
      - msa-network

  todos-api:
    build: ./todos-api
    expose:
      - "8082"
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    networks:
      - msa-network

  frontend:
    build: ./frontend
    expose:
      - "8080"
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
    networks:
      - msa-network

  log-message-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    networks:
      - msa-network

  redis:
    image: redis:7.0
    ports:
      - "6380:6379"   # ⚠️ Cambia a expose: "6379" si no lo necesitas externo
    networks:
      - msa-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - msa-network

  gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users-api
      - auth-api
      - todos-api
      - frontend
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
