version: '3.8'

services:
  auth-api-eu:
    build: ./auth-api
    ports:
      - "8001:8000"
    environment:
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api-eu:8083
      - JWT_SECRET=PRFT
    networks:
      - eu-network

  users-api-eu:
    build: ./users-api
    ports:
      - "8084:8083"
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
    networks:
      - eu-network

  log-message-processor-eu:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis-eu
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis-eu
    networks:
      - eu-network

  todos-api-eu:
    build: ./todos-api
    ports:
      - "8085:8082"
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis-eu
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis-eu
    networks:
      - eu-network

  frontend-eu:
    build: ./frontend
    ports:
      - "8086:8080"
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api-eu:8000
      - TODOS_API_ADDRESS=http://todos-api-eu:8082
    networks:
      - eu-network
    labels:
      - "traefik.http.routers.frontend-eu.rule=PathPrefix(`/eu`)"
      - "traefik.http.services.frontend-eu.loadbalancer.server.port=8080"

  redis-eu:
    image: redis:7.0
    ports:
      - "6380:6379"
    networks:
      - eu-network

networks:
  eu-network:
    driver: bridge