version: '3.8'

services:
  auth-api:
    image: lacragh/auth-api:latest # Usa la imagen preconstruida en Docker Hub
    expose:
      - "8000"
    environment:
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api.lacragh.koyeb.app # URL pública de users-api
      - JWT_SECRET=PRFT

  users-api:
    image: lacragh/users-api:latest # Usa la imagen preconstruida en Docker Hub
    expose:
      - "8083"
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083

  todos-api:
    image: lacragh/todos-api:latest # Usa la imagen preconstruida en Docker Hub
    expose:
      - "8082"
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=<REDIS_URL> # URL de Redis proporcionada por Koyeb
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel

  frontend:
    image: lacragh/frontend:latest # Usa la imagen preconstruida en Docker Hub
    expose:
      - "8080"
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api.lacragh.koyeb.app # URL pública de auth-api
      - TODOS_API_ADDRESS=http://todos-api.lacragh.koyeb.app # URL pública de todos-api

  log-message-processor:
    image: lacragh/log-message-processor:latest # Usa la imagen preconstruida en Docker Hub
    environment:
      - REDIS_HOST=<REDIS_URL> # URL de Redis proporcionada por Koyeb
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel

  redis:
    image: redis:7.0
    expose:
      - "6379" # Solo expón el puerto interno si es necesario

  gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf