apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: docker.io/lacragh/auth-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET
              value: "PRFT"
            - name: HOST
              value: "0.0.0.0"  # Add this to make your app listen on all interfaces
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: auth-api