name: CI/CD Pipeline - Development

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up DockerHub Login
      uses: docker/login-action@v2
      with:
        username: luischarria11
        password: docker123

    - name: Build auth-api
      run: |
        docker build -t luischarria11/auth-api ./auth-api

    - name: Build users-api
      run: |
        docker build -t luischarria11/users-api ./users-api

    - name: Build todos-api
      run: |
        docker build -t luischarria11/todos-api ./todos-api

    - name: Build frontend
      run: |
        docker build -t luischarria11/frontend ./frontend

    - name: Push Docker images
      run: |
        docker push luischarria11/auth-api
        docker push luischarria11/users-api
        docker push luischarria11/todos-api
        docker push luischarria11/frontend
