name: CI/CD Pipeline - Development

on:
  push:
    branches:
      - master
      - patron1
  pull_request:
    branches:
      - master
      - patron1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up DockerHub Login
      uses: docker/login-action@v2
      with:
        username: lacragh
        password: victor9043

    - name: Build auth-api
      run: |
        docker build -t lacragh/auth-api ./auth-api

    - name: Build users-api
      run: |
        docker build -t lacragh/users-api ./users-api

    - name: Build todos-api
      run: |
        docker build -t lacragh/todos-api ./todos-api

    - name: Build frontend
      run: |
        docker build -t lacragh/frontend ./frontend

    

    - name: Push Docker images
      run: |
        docker push lacragh/auth-api
        docker push lacragh/users-api
        docker push lacragh/todos-api
        docker push lacragh/frontend
